#!/bin/bash
#05/11/2018
echo "Script for Arrays"
array_var=(1 2 3 4 5 6)

echo ${array_var[0]}
echo ${array_var[1]}

echo "List all elements: "
echo ${array_var[*]}

echo "List all elements(alternative method): "
echo ${array_var[@]}

echo "Number of elements: ${#array_var[*]}"
labip[0]="192.168.1.1"
labip[1]="192.168.1.10"

echo ${labip[0]}
echo ${labip[1]}

echo "List all elements: "
echo ${labip[*]}

echo "Number of elements: ${#labip[*]}"

echo "End of scirpt"
