#!/bin/bash
#05/11/2018

echo "script for logical operators"

if [ $# -ne 4 ]; then
 echo "Usage: logicalOP num1 num2 num3 num4"
 echo "     Please enter 4 numbers"
 exit 255
fi

echo Parameters: $1 $2 $3 $4
echo Showing logical AND
if [[ $1 -eq $2 && $3 -eq $4 ]]; then
 echo Clause 1
else 
 echo Clause 2
fi

echo Showing logical OR

if [[ $1 -eq $2 || $3 -eq $4 ]]; then
 echo Clause 1
else 
 echo Clause 2
fi

echo "End of scipt"
exit 0

