#!/bin/bash
#05/11/2018
echo "Script for Loop"
x=1
while [ $x -le 10 ]
do
 echo x: $x
 let x++
done

echo "End of part1"

echo "second part"
x=1
while [$x -le 0]
do 
 echo x: $x
 mkdir folder$x
 let x++
done
echo "End of script2"


tput clear
echo "Nested Loop"
row=1
while [ $row -le 20 ]
do 
 col=1
 while [ $col -le 20 ]
 do 
   echo -n "#"
   let col++
 done 
 echo ""
 let row++
done
exit 0
