#!/bin/bash
cls()
{
 tput clear
 return 0
}

home()
{
 tput cup 0 0 
 return 0
}

end()
{
 let x=$COLUMNS-1
 tput cup $LINES $x
 echo -n "X"
}

bold()
{
 tput smso
}

unbold()
{
 tput rmso
}

underline()
{
 tput smul
}

normalline()
{
 tput rmul
}

##code starts here

rc=0 #initialization return code=0
if [ $# -ne 1 ]; then
 echo "Usage: script parameter"
 echo "Where parameter can be: "
 echo "home -put an X at the home position"
 echo "cls  -clear the terminal screen"
 echo "end  -put an X at the last screen postion"
 echo "bold -bold the following output"
 echo "underline -underline the following output"
 exit 255
fi

param=$1
if [ "$param" = "home" ]; then
 echo "Calling subroutine home."
 home
 echo -n "X"
elif [ "$param" = "cls" ]; then
 cls
elif [ "$param" = "end" ]; then 
 echo "Calling subroutine end."
 end
elif [ "$param" = "bold" ]; then
 echo "Calling subroutine bold."
 bold
 echo "After calling subroutine bold"
 unbold 
 echo "After calling unbold"
elif [ "$param" = "underline" ]; then
 echo "Calling underline"
 underline
 echo "After underline"
 normalline
 echo "After normalline"
else 
 echo "Unknown parameter: $param"
 rc=1
fi 

exit $rc

 
